### SENTRY
name: Sentry release information
on: [push]
jobs:
  Sentry-Release-Information:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./scripts/build.sh
        shell: bash
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
