name: Sentry release information
on:
  push:
    branches:
      - main
jobs:
  Sentry-Release-Information:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./scripts/sentry.sh
        shell: bash
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
